branch-defaults:
  default:
    environment: klinker-eb-docker
    group_suffix: null
global:
  application_name: sample-eb-docker
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
